baseurl = ""
relativeurls = true
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 50
theme = "hugo-theme-techlog-simple"
#theme = "hugo-universal-theme"

relativeURLs = true

[taxonomies]
    tag = "tags"
    category = "categories"